### ISSUE TITLE
Broken after upgrade to Meteor 1.4 ?

### ISSUE THREAD

**Issue by nzwade** [3stack-software/celery-shoot#4]
Hi @nathan-muir,

Thanks very much for creating this package. I managed to upgrade my install to Meteor 1.4.1.1 but now I find that when the method which calls the Celery task is run, Meteor becomes inaccessible and CPU usage spikes to 100%. The logs provide the below error. Oddly when checking Celery I can see that the task was received. Do you have any ideas?

> Exception while invoking method 'start_robotics' { stack: undefined, source: 'method' }
> 
> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> node npm-rebuild.js
> 
> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> node npm-rebuild.js
> 
> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> [178.62.83.33]npm WARN meteor-dev-bundle@0.0.0 No description
> npm WARN meteor-dev-bundle@0.0.0 No repository field.
> npm WARN meteor-dev-bundle@0.0.0 No license field.
> Error: Uncaught, unspecified "error" event. ([object Object])
>     at Consumer.emit (events.js:144:17)
>     at Consumer._channelClosed (/bundle/bundle/programs/server/npm/node_modules/meteor/3stack_celery-shoot/node_modules/celery-shoot/node_modules/amqp-coffee/bin/src/lib/Consumer.js:202:14)
>     at Consumer._channelClosed (/bundle/bundle/programs/server/npm/node_modules/meteor/3stack_celery-shoot/node_modules/celery-shoot/node_modules/amqp-coffee/bin/src/lib/Consumer.js:4:61)
>     at Consumer.Channel._onChannelMethod (/bundle/bundle/programs/server/npm/node_modules/meteor/3stack_celery-shoot/node_modules/celery-shoot/node_modules/amqp-coffee/bin/src/lib/Channel.js:349:16)
>     at Connection._onMethod (/bundle/bundle/programs/server/npm/node_modules/meteor/3stack_celery-shoot/node_modules/celery-shoot/node_modules/amqp-coffee/bin/src/lib/Connection.js:673:39)
>     at AMQPParser.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/3stack_celery-shoot/node_modules/celery-shoot/node_modules/amqp-coffee/bin/src/lib/Connection.js:4:61)
>     at emitThree (events.js:97:13)
>     at AMQPParser.emit (events.js:175:7)
>     at AMQPParser.parseMethodFrame (/bundle/bundle/programs/server/npm/node_modules/meteor/3stack_celery-shoot/node_modules/celery-shoot/node_modules/amqp-coffee/bin/src/lib/AMQPParser.js:111:19)
>     at AMQPParser.frameEnd (/bundle/bundle/programs/server/npm/node_modules/meteor/3stack_celery-shoot/node_modules/celery-shoot/node_modules/amqp-coffee/bin/src/lib/AMQPParser.js:81:16)
> /opt/meteord/run_app.sh: line 21:     8 Killed                  npm install --unsafe-perm
> /opt/meteord/run_app.sh: line 21:     8 Killed                  npm install --unsafe-perm
> [178.62.83.33]> node npm-rebuild.js
> [178.62.83.33]/opt/meteord/run_app.sh: line 21:     8 Killed                  npm install --unsafe-perm

Much appreciated,

Wade

**Comment by nathan-muir** [comment]
Hey @nzwade 

I've been pretty lazy, two of my apps that use this package are still running Meteor@1.2.1, so I haven't run into this yet.

I'll take a quick look - and see if anything pops out.

**Comment by nathan-muir** [comment]
Okay, can you try it out with `4.3.0-rc.0`?

**Comment by nzwade** [comment]
Hi Nathan,

Thanks for taking a look and the quick reply, where can i download 4.3.0-rc.0 ?

**Comment by nathan-muir** [comment]
Yeah, not sure how to do it via the CLI.

Either update the `.meteor/packages` file to have the version - ie `3stack:celery-shoot@4.3.0-rc.0`, or update `.meteor/versions`

**Comment by nzwade** [comment]
hi @nathan-muir 

The package i'm using is `meteor-celery-connect` - could this please be updated too. I edited the versions file and it worked at first, but then after i ran the method my CPU usage spiked again causing meteor to crash and the following error: 

> /opt/meteord/run_app.sh: line 44:    32 Killed                  node main.js

**Comment by nathan-muir** [comment]
I don't have the time to do any further diagnosis of this issue.

You don't have to rely on me though - `git clone` both `meteor-celery-connect` and `celery-shoot` into your apps `/packages` directory and start hacking.

From the stack trace you posted though - the issue mightn't even be in this package, it could be in the rabbitmq library we're using called `amqp-coffe`
